export type TaskStatus = 'backlog'|'ready'|'planning'|'implementing'|'testing'|'review'|'security_review'|'quality_gate'|'debugging'|'blocked'|'done'|'failed';
export type WorkerErrorType = 'quota'|'timeout'|'auth'|'unavailable'|'execution'|'unknown';
export type AgentRole = 'product'|'architect'|'developer'|'tester'|'reviewer'|'security'|'debugger';
export type Risk = 'low'|'medium'|'high'|'critical';
export interface Task { id:string; version:number; title:string; type:string; domain?:string; priority?:number; status:TaskStatus; assigned_role?:AgentRole; objective:string; acceptance_criteria:string[]; scope?:{allowed?:string[]; forbidden?:string[]}; quality_gates?:string[]; risk?:Risk; human_approval?:boolean; max_attempts?:number; escalation?:{after_attempts:number; role:AgentRole}; depends_on?:string[]; generated_by?:string; parent_task?:string; }
export interface Worker { id:string; provider:string; model:string; command?:string; argsTemplate?:string[]; capabilities:string[]; enabled?:boolean; cooldownSeconds?:number; reliability?:number; quality?:number; cost?:number; }
export interface Config { security?:{require_isolated_worker?:boolean;allowed_commands?:string[];denied_commands?:string[];max_output_chars?:number;deny_secret_env_to_command_workers?:boolean}; defaults:{max_task_attempts:number; require_clean_git:boolean; auto_commit:boolean; auto_merge:boolean; daemon_interval_seconds:number; max_context_chars:number; run_timeout_ms:number; max_recovery_attempts:number; heartbeat_interval_seconds:number; resource_budget?:number; max_parallel_workers?:number}; workers:Worker[]; quality?:{gates?:Record<string,{command:string;required?:boolean}>}; routing?:Record<string,{preferred?:string[]}>; policy?:{forbidden_commands?:string[]; protected_paths?:string[]; require_review_for?:Risk[]; max_changed_files?:number}; }
export interface WorkerRequest { projectPath:string; model:string; prompt:string; timeoutMs:number; command?:string; provider?:string; conversationId?:string; onEvent?:(event:WorkerStreamEvent)=>void; }
export interface WorkerStreamEvent { type:string; raw:string; message?:string; conversationId?:string; status?:string; }
export interface WorkerResult { success:boolean; output:string; exitCode:number|null; durationMs:number; errorType?:WorkerErrorType; conversationId?:string; turns?:number; usage?:unknown; events?:number; }
export interface AgentResult { role:AgentRole; success:boolean; output:string; workerId:string; model:string; }
export interface WorkerHealth { workerId:string; successes:number; failures:number; consecutiveFailures:number; lastSuccess?:string; lastFailure?:string; cooldownUntil?:string; avgDurationMs?:number; }
